name: Build, Test & Publish to PyPI

on:
  release:
    types: [published]
  push:
    # tags:
    #   - 'v*' # Alternative: only build for tags.
  pull_request:

jobs:
  build:
    name: Build wheel & source package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Build
        run: uv build --out-dir dist && ls dist
      - uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/*

  upload_pypi:
    needs:
      - build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag
    permissions:
        id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  build_conda:
    name: Build wheel & conda package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: latest
          cache: true
      - name: Build conda package
        run: pixi publish --target-dir dist && ls dist/
      - uses: actions/upload-artifact@v7
        with:
          name: conda-package-distributions
          path: dist/*

  upload_release:
    needs:
      - build
      - build_conda
    runs-on: ubuntu-latest
    steps:
      - name: Download all the dists A
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist
      - name: Download all the dists B
        uses: actions/download-artifact@v8
        with:
          name: conda-package-distributions
          path: dist
      - name: Show files under `dist`
        run: ls -lh dist/otfkmc*
      - name: Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
